image: archlinux/base

pages:
    stage: deploy
    script:
        - pacman --noconfirm -Sy pandoc sassc python-setuptools yq
        - ./generate.sh
    artifacts:
        paths:
            - public
    only:
        - master
