image: debian:testing-slim

before_script:
    - apt update
    - apt -y install pandoc ruby-sass

pages:
    stage: deploy
    script: ./generate.sh
    artifacts:
        paths:
            - public
    only:
        - master
