image: debian:testing-slim

before_script:
    - apt update
    - apt -y install pandoc sassc

pages:
    stage: deploy
    script: src/generate.sh
    artifacts:
        paths:
            - public
    only:
        - master
